### ISSUE TITLE
svmlinear fix

### ISSUE THREAD

**Issue by junchaowu** [erelsgl/limdu#50]
The svmlinear doesn't work.
Since I don't have permission to push diff, I just post here:
```
diff --git a/classifiers/svm/SvmLinear.js b/classifiers/svm/SvmLinear.js
index 4688a71..8d2d272 100644
--- a/classifiers/svm/SvmLinear.js
+++ b/classifiers/svm/SvmLinear.js
@@ -16,46 +16,41 @@
  *  <li>multiclass - if true, the 'classify' function returns an array [label,score]. If false (default), it returns only a score.
  */
 
+var util  = require('util')
+  , child_process = require('child_process')
+  , exec = require('child_process').exec
+  , fs   = require('fs')
+  , svmcommon = require('./svmcommon')
+  , _ = require('underscore')._
+
+var FIRST_FEATURE_NUMBER=1;  // in lib linear, feature numbers start with 1
+
 function SvmLinear(opts) {
-	if (!SvmLinear.isInstalled()) {
-		var msg = "Cannot find the executable 'liblinear_train'. Please download it from the LibLinear website, and put a link to it in your path.";
-		console.error(msg)
-		throw new Error(msg);
-	}
 	this.learn_args = opts.learn_args || "";
 	this.model_file_prefix = opts.model_file_prefix || null;
 	this.bias = opts.bias || 1.0;
 	this.multiclass = opts.multiclass || false;
 	this.debug = opts.debug||false;
-  	this.train_command = opts.train_command || 'liblinear_train'
-  	this.test_command = opts.test_command || 'liblinear_test'
-  	this.timestamp = ""
+	this.train_command = opts.train_command || 'liblinear_train'
+	this.test_command = opts.test_command || 'liblinear_test'
+	this.timestamp = ""
 
 	if (!SvmLinear.isInstalled()) {
-                var msg = "Cannot find the executable 'liblinear_train'. Please download it from the LibLinear website, and put a link to it in your path.";
-                console.error(msg)
-                throw new Error(msg);
-        }
+			var msg = "Cannot find the executable 'liblinear_train'. Please download it from the LibLinear website, and put a link to it in your path.";
+			console.error(msg)
+			throw new Error(msg);
+	}
 }
 
 SvmLinear.isInstalled = function() {
 	try {
-	    var result = execSync(this.train_command);
+	    var result = child_process.execSync(this.train_command);
 	} catch (err) {
 	    return false
 	}
 	return true
 };
 
-var util  = require('util')
-  , child_process = require('child_process')
-  , exec = require('child_process').exec
-  , fs   = require('fs')
-  , svmcommon = require('./svmcommon')
-  , _ = require('underscore')._
-
-var FIRST_FEATURE_NUMBER=1;  // in lib linear, feature numbers start with 1
-
 
 SvmLinear.prototype = {
 		trainOnline: function(features, expected) {
```

**Comment by erelsgl** [comment]
Can you explain in words (a) what the problem was and (b) what your
solution does? Thanks

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by junchaowu** [comment]
basically `SvmLinear.isInstalled()` method is misused and duplicated.

**Comment by junchaowu** [comment]
There are two isInstalled() check. The first one is unnecessary.
Second inside the isInstalled, `execSync` should be `child_process.execSync`

**Comment by erelsgl** [comment]
Fixed, please verify

**Comment by junchaowu** [comment]
thanks can you cut a release?

**Comment by erelsgl** [comment]
Published version 0.9.2 to npm

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by junchaowu** [comment]
I don't think the patch fixes the bug.

I notice that `liblinear_train` will always return exit code 1.  The node will still throw err.

You should change it to `liblinear_train .` . Given a folder directory, it will return exit code 0.

**Comment by erelsgl** [comment]
Fixed, is it OK now?

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*
